[package]
name = "ijsm_x86"
version = "0.1.0"
authors = ["Brian Heylin <git@heylin.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
